repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: check-added-large-files

    - repo: https://github.com/psf/black
      rev: 24.1.1
      hooks:
          - id: black
            language_version: python3.11

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.8.0
      hooks:
          - id: mypy
            additional_dependencies:
                [types-all, pytest, numpy, torch, fastapi, pydantic, aiohttp]
            args: [--strict, --no-warn-unused-ignores, --python-version=3.11]

    - repo: https://github.com/PyCQA/pylint
      rev: v3.0.3
      hooks:
          - id: pylint
            args:
                [
                    "--load-plugins=pylint.extensions.typing",
                    "--django-settings-module=config.settings",
                ]

    - repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
            args: [--max-line-length=88]
            additional_dependencies:
                [flake8-typing-imports, flake8-annotations, flake8-docstrings]

    - repo: https://github.com/pre-commit/pyright
      rev: v1.1.350
      hooks:
          - id: pyright
            args: [--level=strict]

    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: [--profile=black]

    - repo: local
      hooks:
          - id: pytest-check
            name: pytest-check
            entry: pytest
            language: system
            pass_filenames: false
            always_run: true
            args: ["--mypy", "--typeguard-packages=src", "-v"]
