version: "3.8"

services:
    fusion-ai-autocoder:
        build:
            context: ..
            dockerfile: docker-templates/Dockerfile
        image: fusion-ai-autocoder:latest
        container_name: fusion-ai-autocoder
        runtime: nvidia # Enables NVIDIA GPU support
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        env_file:
            - ../.env
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
            - AZURE_FOUNDRY_ENDPOINT=${AZURE_FOUNDRY_ENDPOINT}
            - AZURE_TENANT_ID=${AZURE_TENANT_ID}
            - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
            - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
            - LOG_LEVEL=${LOG_LEVEL:-INFO}
            - PORT=${PORT:-8080}
            - API_KEY=${API_KEY}
            - ENABLE_GPU=${ENABLE_GPU:-true}
        ports:
            - "${PORT:-8080}:8080"
        volumes:
            - ../logs:/app/logs
            - ../data:/app/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s
        command: ["python", "-m", "src.api"]
        restart: unless-stopped
